// MESSAGE TO SEND 



//Error message
#define INVALID_USER "INVALID USER"
#define UNKNOW_OPTION "UNKNOW_OPTION"
#define INVALID_OPTION_FORMAT "INVALID_OPTION_FORMAT"
#define IMAGE_NOT_FOUND "IMAGE_NOT_FOUND"
#define ERROR_OPEN_IMAGE "ERROR_OPEN_IMAGE PATH:"
#define AUDIO_NOT_FOUND "AUDIO_NOT_FOUND"
#define ERROR_OPEN_AUDIO_FILE "ERROR_OPEN_AUDIO_FILE PATH:"


//Log message
#define USER_INIT "user login: "


//KEY MESSAGE
#define GET_IMAGE "GET_IMAGE" 
#define EXIT "EXIT"
#define GET_BYTES "GET_BYTES"
#define GET_AUDIO "GET_AUDIO"