// MESSAGE TO SEND 



//Error message
#define INVALID_USER "INVALID USER"
#define UNKNOW_OPTION "UNKNOW_OPTION"
#define INVALID_OPTION_FORMAT "INVALID_OPTION_FORMAT"
#define IMAGE_NOT_FOUND "IMAGE_NOT_FOUND"
#define ERROR_OPEN_IMAGE "ERROR_OPEN_IMAGE PATH:"
#define AUDIO_NOT_FOUND "AUDIO_NOT_FOUND"
#define ERROR_OPEN_AUDIO_FILE "ERROR_OPEN_AUDIO_FILE PATH:"
#define ERROR_OPEN_MUSIC_FILE "ERROR_OPEN_MUSIC_FILE"
#define PLAYLIST_NAME_ERROR "PLAYLIST_NAME_ERROR"
#define PLAYLIST_CREATE_ERROR "PLAYLIST_CREATE_ERROR"
#define ERROR_USER_INFORMATION "ERROR_USER_INFORMATION"
#define INVALID_DATA "INVALID_DATA"
//SUCCESS MESSAGE

#define PLAYLIST_WAS_CREATED "PLAYLIST_WAS_CREATED"

//Log message
#define USER_INIT "user login: "
#define COMMAND "COMMAND:"
#define SEND_AUDIO "SEND_AUDIO Path:"


//KEY MESSAGE
#define GET_IMAGE "GET_IMAGE" 
#define EXIT "EXIT"
#define GET_BYTES "GET_BYTES"
#define GET_AUDIO "GET_AUDIO"
#define CREATE_PLAYLIST "CREATE_PLAYLIST"
#define LOGIN "LOGIN"
#define GET_ALL_SONGS "GET_ALL_SONGS"
#define MATCH_MUSIC_PLAYLIST "MATCH_MUSIC_PLAYLIST"
